# Álgebra Lineal con Python

Recordemos que si damos $n*m$ números reales, entonces podemos crear un arreglo (una matriz):
$$A_{m\times n}=\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}$$

y al conjunto de matrices con coeficientes en $\mathbb{R}$ lo denotamos $\text{Mat}_{m\times n}(\mathbb{R})$.

Vimos que el conjunto $\text{Mat}_{m\times n}(\mathbb{R})$ es un espacio vectorial de dimensión $n*m$. También, asociamos dos subespacios fundamentales:

- El **Espacio nulo** de $A_{n\times n}$:
$$\text{Nul}(A)=\{ x\in \mathbb{R}^{n} : Ax=0 \}.$$
Al ser un subespacio vectorial, tiene dimensión la cual denotaremos por $\dim(\text{Nul}(A))=n(A)$.

- El **Espacio columna** de $A_{m\times n}$, \text{Col}(A), es el espacio generado por las columnas de $A$. Una propiedad importante es que 
$$b\in \text{Col}(A) \ \ \text{si y sólo si} \ \ Ax=b \ \ \text{es consistente}.$$
Al ser un subespacio vectorial, tiene dimensión la cual denotaremos por $\dim(\text{Col}(A))=r(A)$.

El **Teorema de la dimensión** afirma que:
$$n = n(A)+r(A).$$

$\color{red}{\text{Teorema fundamental}}$. Si $A_{n\times n}$. Entonces las siguientes afirmaciones son equivalentes:


1.   $A$ es invertible.
2.   $\text{Nul}(A)=\{0\}$
3.   El sistema $Ax=b$ tiene una única solución para cada vector, $b$, de dimensión $n$.
4.   $A$ es equivalente a la matriz identidad $I_{n}$.
5.   Las columnas (y renglones) de $A$ son linealmente independientes.
6.   $\det(A)\neq 0$.
7.   $n(A)=0$.
8.   $r(A)=n$.










### Aritmética básica en Python

In [ ]:
1+1

2

In [ ]:
3.5 - 2.6 

0.8999999999999999

In [ ]:
2*3 

6

In [ ]:
2**3

8

In [ ]:
4/3

1.3333333333333333

In [ ]:
4//3 # división al piso

1

In [ ]:
type(2), type(2.0), type("2") # La función type(obj) nos dice el tipo de objeto con el que se está trabajando.

(int, float, str)

### Debug: 
$$\text{nombre} = \text{objeto}$$

Debug: $\text{print(variable)}$

In [ ]:
variable = "Hola"

x = 5 

Cesar = {1, 2, "perro"} 

print(variable) 

print(x) 


Hola
5


In [ ]:
variable + str(x)  

'Hola5'

### Listas

$L=[a_{1}, a_{2}, \dots, a_{n}]$

In [ ]:
L = [1, 2, 3, 4, 5]

M = [6, 7, 8, 9 , 10]

N = [11, 12, 13]

print(L)
print(M)  # me muestra el resultado
print(N)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[11, 12, 13]


In [ ]:
type(L) 

list

In [ ]:
L_set = set(L) 

L_set 

{1, 2, 3, 4, 5}

In [ ]:
L_lista = list(L_set) 
L_lista 

[1, 2, 3, 4, 5]

In [ ]:
L + M # concatena (no realiza operaciones vectoriales).

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
L + M + N 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

### NumPy

- Un vector = arreglo 1D en Python
- Una matriz = arreglo 2D en Python

In [ ]:
import numpy as np 

In [ ]:
L_vector = np.array(L) # Convertir una lista en un vector

L_vector 

array([1, 2, 3, 4, 5])

In [ ]:
type(L_vector) 

numpy.ndarray

In [ ]:
M_vector = np.array(M) 

N_vector = np.array(N)

print(M_vector)
print(N_vector)

[ 6  7  8  9 10]
[11 12 13]


In [ ]:
len(L_vector), len(M_vector), len(N_vector)

(5, 5, 3)

In [ ]:
L_vector + M_vector # suma vectorial

array([ 7,  9, 11, 13, 15])

## Creando matrices con NumPy: El método `solve( , )`


In [ ]:
A = np.array([1, 2, 1, 3]).reshape((2,2))
A 

array([[1, 2],
       [1, 3]])

In [ ]:
B = np.array([1,3]) 

$$AX=B$$

In [ ]:
X = np.linalg.solve(A,B) 

X

[-3.  2.]
